FROM ruby:3.0.2

# Set default locale for the environment
ENV LC_ALL C.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8

RUN gem install bundler:2.2.29

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY Gemfile Gemfile.lock jekyll-text-theme.gemspec ./
RUN bundle install

EXPOSE 4000

CMD ["bundle", "exec", "jekyll", "help"]
